{
 "title": "Products",
 "time": { "from": "2022-01-18T08:41:30.114Z", "to": "2022-01-18T10:41:30.114Z" },
 "panels": [
  {
   "title": "Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(product_page_observation_second_sum[24h])) by (job) / sum(rate(product_page_observation_second_count[24h]))  by (job) "
    }
   ]
  },
  {
   "title": "Purchased Products",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(product_page_observation_second_count{purchase=\"true\"}) by (productID)",
     "legendFormat": "{{productID}}"
    }
   ]
  },
  {
   "title": "Average Product Duration By Purchase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(product_page_observation_second_sum{purchase=\"true\"}[24h])) by (job) / sum(rate(product_page_observation_second_count{purchase=\"true\"}[24h]))  by (job) ",
     "legendFormat": "Purchased"
    },
    {
     "expr": "sum(rate(product_page_observation_second_sum{purchase=\"false\"}[24h])) by (job) / sum(rate(product_page_observation_second_count{purchase=\"false\"}[24h]))  by (job) ",
     "legendFormat": "Not Purchased"
    }
   ]
  },
  {
   "title": "Average Duration by Product",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(product_page_observation_second_sum)  by (productID)  /sum(product_page_observation_second_count)  by (productID)  )",
     "legendFormat": "{{productID}}"
    }
   ]
  }
 ]
}